[package]
name = "example_scrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper="0.16.0"
error-stack = "0.3.1"
reqwest = { version="0.11.18", features=["blocking"] }
